# Generated by Django 4.1.7 on 2023-03-08 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("icpc", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="competition",
            unique_together={("team", "instance", "year")},
        ),
    ]
